#! /bin/sh

sxhkd &
feh --bg-scale /home/anthony/Pictures/walls/ump.jpg
picom &
./.config/polybar/start.sh lit &
touch /tmp/cover.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          30

bspc config top_padding         10
bspc config bottom_padding      20
bspc config left_padding        79
bspc config right_padding       79

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a discord desktop='9' focus=off follow=off
